[package]
name = "sgvcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio ={ version = "1.38.0", features = ["full"] }
sha1 = "0.10.6"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
chrono = "0.4.38"